name: Build AdGuard Additional DNS filters

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write  # Crucial for pushing commits back to the repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run build
        run: python scripts/build.py

      - name: Commit changes if needed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          
          # Check if there are any staged changes, commit and push if true
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Auto update filters"
            git push
          else
            echo "No changes to commit."
          fi
